### ISSUE TITLE
NameError: name 'rfe_dt_preds' is not defined for kaggle_hgst_end2end.ipynb

### ISSUE THREAD

**Issue by Jian-Zhang** [chauhankaranraj/ceph_drive_failure#2]
I was using this great end to end example, but met some issues at the last Mlflow logging part. 

NameError: name 'rfe_dt_preds' is not defined, how to define rfe_dt_preds? 

[https://github.com/chauhankaranraj/ceph_drive_failure/blob/master/kaggle_hgst_end2end.ipynb](url)

**Comment by Jian-Zhang** [comment]
I figured out how to resolve it.

**Comment by chauhankaranraj** [comment]
Hi @Jian-Zhang, thanks for letting me know of the issue :)
It should have been `dt_preds` instead of `rfe_dt_preds` (or preds from any other model defined in the notebook). It should be fixed now, but let me know if it still doesn't work.
